# [ 버전 확인 명령어들 ]
alias pyv='python3 --version'
alias pipv='pip3 --version'
alias nodev='node --version'
alias npmv='npm --version'
alias javav='java --version'
alias gitv='git --version'
alias dockerv='docker --version'
alias brewv='brew --version'
alias redisv='redis-server --version'
alias zshv='zsh --version'
